version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    image : todo-list-challenge
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    container_name: todo-db
    environment:
      MYSQL_DATABASE: 'todo-list'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: